services:
  webui:
    build: .
    ports:
      - "7860:7860"
    environment:
      - "ARGS=--listen --enable-insecure-extension-acces"
      - "UI=forge"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]